name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Deploy
        run: |
          dotnet nuget push MiniRazor.Runtime/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
          dotnet nuget push MiniRazor.Compiler/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
          dotnet nuget push MiniRazor.CodeGen/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
          dotnet nuget push MiniRazor/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}

      - name: Notify Discord
        run: |
          curl '${{ secrets.DISCORD_WEBHOOK }}' \
            --data-raw '{"content":"**MiniRazor** new version released!\nRef: `${{ github.ref }}`\nChangelog: <https://github.com/Tyrrrz/MiniRazor/blob/${{ github.sha }}/Changelog.md>"}' \
            -H 'content-type: application/json'
