name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Get release version
        id: get-version
        uses: dawidd6/action-get-tag@v1

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Deploy
        run: |
          dotnet nuget push MiniRazor.Runtime/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
          dotnet nuget push MiniRazor.Compiler/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
          dotnet nuget push MiniRazor.CodeGen/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
          dotnet nuget push MiniRazor/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}

      - name: Notify Discord
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            {
              "ContentType": "application/json; charset=UTF-8"
            }
          payload: |
            {
              "content": "**MiniRazor** new version released!\nVersion: `${{ steps.get-version.outputs.tag }}`\nChangelog: <https://github.com/Tyrrrz/MiniRazor/blob/${{ steps.get-version.outputs.tag }}/Changelog.md>"
            }