name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100

      - name: Install .NET (v2.1)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 2.1.100

      - name: Build & test
        run: dotnet test --configuration Release --logger GitHubActions

      - name: Upload coverage (.NET v5.0)
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: MiniRazor.Tests/bin/Release/Coverage.net5.0.xml

      - name: Upload coverage (.NET v2.1)
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: MiniRazor.Tests/bin/Release/Coverage.netcoreapp2.1.xml
